name: Node CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1️⃣ Checkout Code
        uses: actions/checkout@v3

      - name: 2️⃣ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 3️⃣ Install Dependencies
        run: npm install

      - name: 4️⃣ Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            rm -rf node-cicd-demo
            git clone https://github.com/piyushalingayat/node-cicd-demo.git
            cd node-cicd-demo
            npm install
            pm2 delete all || true
            pm2 start server.js
